server:
  port: 2734

eureka:
  client:
    service-url:
      defaultZone: http://${HOST_EUREKA}:8761/eureka

spring:
  application:
    name: security

security:
  jwt:
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem